### PR TITLE
Bumped versions of prometheus, Alert manager and SNMP exporter, changes to HA

### PR DESCRIPTION
**Pull request by madeinoz67**
Bumped versions of:

- prometheus: 2.4.3
- alertmanager: 0.15.2
- snmpexporter: 0.13.0
- pushgateway: 0.6.0

I have not included host exporter due to the breaking changes

Alert manager config around HA has changed, updated defaults to reflect these changes

### CODE REVIEW

**Comment by madeinoz67** [comment]
closes #70

**Comment by ernestas-poskus** [comment]
Hey thanks for making these changes I have only checked push_gateway so far looks like you are missing

```
$ g diff vars/
diff --git a/vars/pushgateway.yml b/vars/pushgateway.yml
index 388f23e..a48e4d4 100644
--- a/vars/pushgateway.yml
+++ b/vars/pushgateway.yml
@@ -7,4 +7,5 @@ prometheus_push_gateway_service_config:
   - ['persistence.file', "{{ prometheus_push_gateway_persistence__file }}"]
   - ['persistence.interval', "{{ prometheus_push_gateway_persistence__interval }}"]
   - ['web.listen-address', "{{ prometheus_push_gateway_web__listen_address }}"]
+  - ['web.route-prefix', "{{ prometheus_push_gateway_web__route_prefix }}"]
   - ['web.telemetry-path', "{{ prometheus_push_gateway_web__telemetry_path }}"]
```

`prometheus_push_gateway_web__route_prefix`

and in defaults/main.yml

```
+prometheus_push_gateway_web__route_prefix:
+# Prefix for the internal routes of web endpoints.
```

**Comment by ernestas-poskus** [comment]
I have pulled most of your changes here https://github.com/ernestas-poskus/ansible-prometheus/pull/72 :bowing_man:

**Comment by madeinoz67** [comment]
Thanks for that @ernestas-poskus

**Pull request closed without merging**
